// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvb2CwdnLufoNz8FqPcx2N-vcpjq7Rfbk',
    appId: '1:251687498014:web:61fc358dfa361517cbd90f',
    messagingSenderId: '251687498014',
    projectId: 'mygp-6777a',
    authDomain: 'mygp-6777a.firebaseapp.com',
    storageBucket: 'mygp-6777a.firebasestorage.app',
    measurementId: 'G-GH0XQ2CFX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUAI33AR_yD2Vxw3BKA0jURZnBxvU7xv4',
    appId: '1:251687498014:android:4982415e44d0f19acbd90f',
    messagingSenderId: '251687498014',
    projectId: 'mygp-6777a',
    storageBucket: 'mygp-6777a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClLZxoD9L_WQXC2PNtl7snFIpEvsZHzdM',
    appId: '1:251687498014:ios:f1cc5c2d5880b2b8cbd90f',
    messagingSenderId: '251687498014',
    projectId: 'mygp-6777a',
    storageBucket: 'mygp-6777a.firebasestorage.app',
    iosBundleId: 'com.example.skindiseasegp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClLZxoD9L_WQXC2PNtl7snFIpEvsZHzdM',
    appId: '1:251687498014:ios:f1cc5c2d5880b2b8cbd90f',
    messagingSenderId: '251687498014',
    projectId: 'mygp-6777a',
    storageBucket: 'mygp-6777a.firebasestorage.app',
    iosBundleId: 'com.example.skindiseasegp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvb2CwdnLufoNz8FqPcx2N-vcpjq7Rfbk',
    appId: '1:251687498014:web:94e07b216f8de065cbd90f',
    messagingSenderId: '251687498014',
    projectId: 'mygp-6777a',
    authDomain: 'mygp-6777a.firebaseapp.com',
    storageBucket: 'mygp-6777a.firebasestorage.app',
    measurementId: 'G-6C3LTF4TEN',
  );
}
